//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proectiq
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestBaseEntities : DbContext
    {
        public TestBaseEntities()
            : base("name=TestBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Material_type> Material_type { get; set; }
        public DbSet<Partners> Partners { get; set; }
        public DbSet<Partners_product> Partners_product { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<Product_type> Product_type { get; set; }
    }
}
