//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proectiq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners_product
    {
        public int ID { get; set; }
        public int ID_Product { get; set; }
        public int ID_Partner { get; set; }
        public Nullable<double> Количество_продукции { get; set; }
        public Nullable<System.DateTime> Дата_продажи { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Product Product { get; set; }
    }
}
