//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proectiq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_type
    {
        public Product_type()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string Название { get; set; }
        public Nullable<double> Коэффициент_типа_продукции { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
